name: Release Plugin ZIP

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Plugin ZIP
        run: |
          mkdir -p courier-center-for-woocommerce
          rsync -av --exclude='.git' \
                    --exclude='.github' \
                    --exclude='.gitignore' \
                    --exclude='tk*' \
                    --exclude='courier-center-for-woocommerce' \
                    . courier-center-for-woocommerce/
          zip -r courier-center-for-woocommerce.zip courier-center-for-woocommerce/

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: courier-center-for-woocommerce.zip
